//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAhorcadoSupremo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Jugador : object
    {
        
        private string ApellidosField;
        
        private string CelularField;
        
        private string CorreoElectronicoField;
        
        private string FechaNacimientoField;
        
        private int IdJugadorField;
        
        private string NombreField;
        
        private string PasswordField;
        
        private int PuntajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador
        {
            get
            {
                return this.IdJugadorField;
            }
            set
            {
                this.IdJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje
        {
            get
            {
                return this.PuntajeField;
            }
            set
            {
                this.PuntajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Partida : object
    {
        
        private int IdPartidaField;
        
        private int estadoField;
        
        private string fechaField;
        
        private int idJugadorField;
        
        private int idPalabraField;
        
        private int idRetadorField;
        
        private char letraField;
        
        private int validacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPartida
        {
            get
            {
                return this.IdPartidaField;
            }
            set
            {
                this.IdPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador
        {
            get
            {
                return this.idJugadorField;
            }
            set
            {
                this.idJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPalabra
        {
            get
            {
                return this.idPalabraField;
            }
            set
            {
                this.idPalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRetador
        {
            get
            {
                return this.idRetadorField;
            }
            set
            {
                this.idRetadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char letra
        {
            get
            {
                return this.letraField;
            }
            set
            {
                this.letraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int validacion
        {
            get
            {
                return this.validacionField;
            }
            set
            {
                this.validacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaGanada", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class PartidaGanada : object
    {
        
        private string fechaPartidaField;
        
        private string jugadorVencidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaPartida
        {
            get
            {
                return this.fechaPartidaField;
            }
            set
            {
                this.fechaPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jugadorVencido
        {
            get
            {
                return this.jugadorVencidoField;
            }
            set
            {
                this.jugadorVencidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Categoria : object
    {
        
        private string DescripcionCategoriaField;
        
        private int IdCategoriaField;
        
        private string NombreCategoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCategoria
        {
            get
            {
                return this.DescripcionCategoriaField;
            }
            set
            {
                this.DescripcionCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCategoria
        {
            get
            {
                return this.NombreCategoriaField;
            }
            set
            {
                this.NombreCategoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Palabra : object
    {
        
        private int IdCategoriaField;
        
        private int IdPalabraField;
        
        private string descripcionField;
        
        private string dificultadField;
        
        private string palabraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPalabra
        {
            get
            {
                return this.IdPalabraField;
            }
            set
            {
                this.IdPalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dificultad
        {
            get
            {
                return this.dificultadField;
            }
            set
            {
                this.dificultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra
        {
            get
            {
                return this.palabraField;
            }
            set
            {
                this.palabraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgresoPartida", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class ProgresoPartida : object
    {
        
        private int estadoField;
        
        private int idPartidaField;
        
        private char letraField;
        
        private string progresoPalabraField;
        
        private int validacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida
        {
            get
            {
                return this.idPartidaField;
            }
            set
            {
                this.idPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char letra
        {
            get
            {
                return this.letraField;
            }
            set
            {
                this.letraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string progresoPalabra
        {
            get
            {
                return this.progresoPalabraField;
            }
            set
            {
                this.progresoPalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int validacion
        {
            get
            {
                return this.validacionField;
            }
            set
            {
                this.validacionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAhorcadoSupremo.IServiceAhorcado")]
    public interface IServiceAhorcado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/VerificarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/VerificarJugadorResponse")]
        System.Threading.Tasks.Task<int> VerificarJugadorAsync(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<string> RegistrarJugadorAsync(ServicioAhorcadoSupremo.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ModificarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/ModificarJugadorResponse")]
        System.Threading.Tasks.Task<string> ModificarJugadorAsync(ServicioAhorcadoSupremo.Jugador editarJugador, string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/recuperarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/recuperarJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Jugador> recuperarJugadorAsync(string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarPuntos", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarPuntosResponse")]
        System.Threading.Tasks.Task<string> ActualizarPuntosAsync(int idJugador, int puntosNuevos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarProgresoPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarProgresoPartidaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProgresoPartidaAsync(char letra, int verificacion, string progresoPalabra, int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarPartidaResponse")]
        System.Threading.Tasks.Task<string> RegistrarPartidaAsync(string fecha, int idRetador, int idPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarJugadorEnPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarJugadorEnPartidaResponse")]
        System.Threading.Tasks.Task<string> RegistrarJugadorEnPartidaAsync(int idPartida, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPartidasDisponibles", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Partida[]> RecuperarPartidasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPartidasJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPartidasJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.PartidaGanada[]> RecuperarPartidasJugadorAsync(string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarCategoria", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarCategoriaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Categoria> RecuperarCategoriaAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPalabra", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPalabraResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Palabra> RecuperarPalabraAsync(int idPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarEstadoPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarEstadoPartidaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstadoPartidaAsync(int estado, int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarProgresoPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarProgresoPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.ProgresoPartida> RecuperarProgresoPartidaAsync(int idPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPalabraCategoria", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPalabraCategoriaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Palabra[]> RecuperarPalabraCategoriaAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Partida> RecuperarPartidaAsync(string fecha, int idRetador, int idPalabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarIdJugadorPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarIdJugadorPartidaResponse")]
        System.Threading.Tasks.Task<int> RecuperarIdJugadorPartidaAsync(int idPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceAhorcadoChannel : ServicioAhorcadoSupremo.IServiceAhorcado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceAhorcadoClient : System.ServiceModel.ClientBase<ServicioAhorcadoSupremo.IServiceAhorcado>, ServicioAhorcadoSupremo.IServiceAhorcado
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceAhorcadoClient() : 
                base(ServiceAhorcadoClient.GetDefaultBinding(), ServiceAhorcadoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceAhorcado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), ServiceAhorcadoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> VerificarJugadorAsync(string correo, string password)
        {
            return base.Channel.VerificarJugadorAsync(correo, password);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarJugadorAsync(ServicioAhorcadoSupremo.Jugador jugador)
        {
            return base.Channel.RegistrarJugadorAsync(jugador);
        }
        
        public System.Threading.Tasks.Task<string> ModificarJugadorAsync(ServicioAhorcadoSupremo.Jugador editarJugador, string idJugador)
        {
            return base.Channel.ModificarJugadorAsync(editarJugador, idJugador);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Jugador> recuperarJugadorAsync(string idJugador)
        {
            return base.Channel.recuperarJugadorAsync(idJugador);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarPuntosAsync(int idJugador, int puntosNuevos)
        {
            return base.Channel.ActualizarPuntosAsync(idJugador, puntosNuevos);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProgresoPartidaAsync(char letra, int verificacion, string progresoPalabra, int idPartida)
        {
            return base.Channel.ActualizarProgresoPartidaAsync(letra, verificacion, progresoPalabra, idPartida);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarPartidaAsync(string fecha, int idRetador, int idPalabra)
        {
            return base.Channel.RegistrarPartidaAsync(fecha, idRetador, idPalabra);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarJugadorEnPartidaAsync(int idPartida, int idJugador)
        {
            return base.Channel.RegistrarJugadorEnPartidaAsync(idPartida, idJugador);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Partida[]> RecuperarPartidasDisponiblesAsync()
        {
            return base.Channel.RecuperarPartidasDisponiblesAsync();
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.PartidaGanada[]> RecuperarPartidasJugadorAsync(string idJugador)
        {
            return base.Channel.RecuperarPartidasJugadorAsync(idJugador);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Categoria> RecuperarCategoriaAsync(int idCategoria)
        {
            return base.Channel.RecuperarCategoriaAsync(idCategoria);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Palabra> RecuperarPalabraAsync(int idPalabra)
        {
            return base.Channel.RecuperarPalabraAsync(idPalabra);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstadoPartidaAsync(int estado, int idPartida)
        {
            return base.Channel.ActualizarEstadoPartidaAsync(estado, idPartida);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.ProgresoPartida> RecuperarProgresoPartidaAsync(int idPartida)
        {
            return base.Channel.RecuperarProgresoPartidaAsync(idPartida);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Palabra[]> RecuperarPalabraCategoriaAsync(int idCategoria)
        {
            return base.Channel.RecuperarPalabraCategoriaAsync(idCategoria);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcadoSupremo.Partida> RecuperarPartidaAsync(string fecha, int idRetador, int idPalabra)
        {
            return base.Channel.RecuperarPartidaAsync(fecha, idRetador, idPalabra);
        }
        
        public System.Threading.Tasks.Task<int> RecuperarIdJugadorPartidaAsync(int idPartida)
        {
            return base.Channel.RecuperarIdJugadorPartidaAsync(idPartida);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAhorcado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAhorcado))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:49522/ServiceAhorcado.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceAhorcadoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceAhorcado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceAhorcadoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceAhorcado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceAhorcado,
        }
    }
}
