//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAhorcado
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Jugador : object
    {
        
        private string ApellidosField;
        
        private string CelularField;
        
        private string CorreoElectronicoField;
        
        private string FechaNacimientoField;
        
        private int IdJugadorField;
        
        private string NombreField;
        
        private string PasswordField;
        
        private int PuntajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador
        {
            get
            {
                return this.IdJugadorField;
            }
            set
            {
                this.IdJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje
        {
            get
            {
                return this.PuntajeField;
            }
            set
            {
                this.PuntajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Partida : object
    {
        
        private int IdPartidaField;
        
        private int estadoField;
        
        private string fechaField;
        
        private int idJugadorField;
        
        private int idPalabraField;
        
        private int idRetadorField;
        
        private char letraField;
        
        private int validacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPartida
        {
            get
            {
                return this.IdPartidaField;
            }
            set
            {
                this.IdPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador
        {
            get
            {
                return this.idJugadorField;
            }
            set
            {
                this.idJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPalabra
        {
            get
            {
                return this.idPalabraField;
            }
            set
            {
                this.idPalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRetador
        {
            get
            {
                return this.idRetadorField;
            }
            set
            {
                this.idRetadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char letra
        {
            get
            {
                return this.letraField;
            }
            set
            {
                this.letraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int validacion
        {
            get
            {
                return this.validacionField;
            }
            set
            {
                this.validacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaGanada", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class PartidaGanada : object
    {
        
        private string fechaPartidaField;
        
        private string jugadorVencidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaPartida
        {
            get
            {
                return this.fechaPartidaField;
            }
            set
            {
                this.fechaPartidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jugadorVencido
        {
            get
            {
                return this.jugadorVencidoField;
            }
            set
            {
                this.jugadorVencidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Categoria : object
    {
        
        private string DescripcionCategoriaField;
        
        private int IdCategoriaField;
        
        private string NombreCategoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCategoria
        {
            get
            {
                return this.DescripcionCategoriaField;
            }
            set
            {
                this.DescripcionCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCategoria
        {
            get
            {
                return this.NombreCategoriaField;
            }
            set
            {
                this.NombreCategoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioArcado.Modelo.POCO")]
    public partial class Palabra : object
    {
        
        private int IdCategoriaField;
        
        private int IdPalabraField;
        
        private string descripcionField;
        
        private string dificultadField;
        
        private string palabraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPalabra
        {
            get
            {
                return this.IdPalabraField;
            }
            set
            {
                this.IdPalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dificultad
        {
            get
            {
                return this.dificultadField;
            }
            set
            {
                this.dificultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra
        {
            get
            {
                return this.palabraField;
            }
            set
            {
                this.palabraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAhorcado.IServiceAhorcado")]
    public interface IServiceAhorcado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/VerificarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/VerificarJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.VerificarJugadorResponse> VerificarJugadorAsync(ServicioAhorcado.VerificarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RegistrarJugadorResponse> RegistrarJugadorAsync(ServicioAhorcado.RegistrarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ModificarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/ModificarJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.ModificarJugadorResponse> ModificarJugadorAsync(ServicioAhorcado.ModificarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/recuperarJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/recuperarJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.recuperarJugadorResponse> recuperarJugadorAsync(ServicioAhorcado.recuperarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarPuntos", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarPuntosResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.ActualizarPuntosResponse> ActualizarPuntosAsync(ServicioAhorcado.ActualizarPuntosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarProgresoPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarProgresoPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.ActualizarProgresoPartidaResponse> ActualizarProgresoPartidaAsync(ServicioAhorcado.ActualizarProgresoPartidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RegistrarPartidaResponse> RegistrarPartidaAsync(ServicioAhorcado.RegistrarPartidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RegistrarJugadorEnPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/RegistrarJugadorEnPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RegistrarJugadorEnPartidaResponse> RegistrarJugadorEnPartidaAsync(ServicioAhorcado.RegistrarJugadorEnPartidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPartidasDisponibles", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPartidasDisponiblesResponse> RecuperarPartidasDisponiblesAsync(ServicioAhorcado.RecuperarPartidasDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPartidasJugador", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPartidasJugadorResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPartidasJugadorResponse> RecuperarPartidasJugadorAsync(ServicioAhorcado.RecuperarPartidasJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarCategoria", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarCategoriaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RecuperarCategoriaResponse> RecuperarCategoriaAsync(ServicioAhorcado.RecuperarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/RecuperarPalabra", ReplyAction="http://tempuri.org/IServiceAhorcado/RecuperarPalabraResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPalabraResponse> RecuperarPalabraAsync(ServicioAhorcado.RecuperarPalabraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAhorcado/ActualizarEstadoPartida", ReplyAction="http://tempuri.org/IServiceAhorcado/ActualizarEstadoPartidaResponse")]
        System.Threading.Tasks.Task<ServicioAhorcado.ActualizarEstadoPartidaResponse> ActualizarEstadoPartidaAsync(ServicioAhorcado.ActualizarEstadoPartidaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarJugador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificarJugadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public VerificarJugadorRequest()
        {
        }
        
        public VerificarJugadorRequest(string correo, string password)
        {
            this.correo = correo;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarJugadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificarJugadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VerificarJugadorResult;
        
        public VerificarJugadorResponse()
        {
        }
        
        public VerificarJugadorResponse(int VerificarJugadorResult)
        {
            this.VerificarJugadorResult = VerificarJugadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarJugador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarJugadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Jugador jugador;
        
        public RegistrarJugadorRequest()
        {
        }
        
        public RegistrarJugadorRequest(ServicioAhorcado.Jugador jugador)
        {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarJugadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarJugadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrarJugadorResult;
        
        public RegistrarJugadorResponse()
        {
        }
        
        public RegistrarJugadorResponse(string RegistrarJugadorResult)
        {
            this.RegistrarJugadorResult = RegistrarJugadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarJugador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModificarJugadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Jugador editarJugador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string idJugador;
        
        public ModificarJugadorRequest()
        {
        }
        
        public ModificarJugadorRequest(ServicioAhorcado.Jugador editarJugador, string idJugador)
        {
            this.editarJugador = editarJugador;
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarJugadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModificarJugadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ModificarJugadorResult;
        
        public ModificarJugadorResponse()
        {
        }
        
        public ModificarJugadorResponse(string ModificarJugadorResult)
        {
            this.ModificarJugadorResult = ModificarJugadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperarJugador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class recuperarJugadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string idJugador;
        
        public recuperarJugadorRequest()
        {
        }
        
        public recuperarJugadorRequest(string idJugador)
        {
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperarJugadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class recuperarJugadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Jugador recuperarJugadorResult;
        
        public recuperarJugadorResponse()
        {
        }
        
        public recuperarJugadorResponse(ServicioAhorcado.Jugador recuperarJugadorResult)
        {
            this.recuperarJugadorResult = recuperarJugadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPuntos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarPuntosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idJugador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int puntosNuevos;
        
        public ActualizarPuntosRequest()
        {
        }
        
        public ActualizarPuntosRequest(int idJugador, int puntosNuevos)
        {
            this.idJugador = idJugador;
            this.puntosNuevos = puntosNuevos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPuntosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarPuntosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ActualizarPuntosResult;
        
        public ActualizarPuntosResponse()
        {
        }
        
        public ActualizarPuntosResponse(string ActualizarPuntosResult)
        {
            this.ActualizarPuntosResult = ActualizarPuntosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProgresoPartida", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarProgresoPartidaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public char letra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int verificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int idPartida;
        
        public ActualizarProgresoPartidaRequest()
        {
        }
        
        public ActualizarProgresoPartidaRequest(char letra, int verificacion, int idPartida)
        {
            this.letra = letra;
            this.verificacion = verificacion;
            this.idPartida = idPartida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProgresoPartidaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarProgresoPartidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActualizarProgresoPartidaResult;
        
        public ActualizarProgresoPartidaResponse()
        {
        }
        
        public ActualizarProgresoPartidaResponse(bool ActualizarProgresoPartidaResult)
        {
            this.ActualizarProgresoPartidaResult = ActualizarProgresoPartidaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarPartida", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarPartidaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idRetador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int idPalabra;
        
        public RegistrarPartidaRequest()
        {
        }
        
        public RegistrarPartidaRequest(string fecha, int idRetador, int idPalabra)
        {
            this.fecha = fecha;
            this.idRetador = idRetador;
            this.idPalabra = idPalabra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarPartidaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarPartidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrarPartidaResult;
        
        public RegistrarPartidaResponse()
        {
        }
        
        public RegistrarPartidaResponse(string RegistrarPartidaResult)
        {
            this.RegistrarPartidaResult = RegistrarPartidaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarJugadorEnPartida", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarJugadorEnPartidaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idPartida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idJugador;
        
        public RegistrarJugadorEnPartidaRequest()
        {
        }
        
        public RegistrarJugadorEnPartidaRequest(int idPartida, int idJugador)
        {
            this.idPartida = idPartida;
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarJugadorEnPartidaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarJugadorEnPartidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrarJugadorEnPartidaResult;
        
        public RegistrarJugadorEnPartidaResponse()
        {
        }
        
        public RegistrarJugadorEnPartidaResponse(string RegistrarJugadorEnPartidaResult)
        {
            this.RegistrarJugadorEnPartidaResult = RegistrarJugadorEnPartidaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPartidasDisponibles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPartidasDisponiblesRequest
    {
        
        public RecuperarPartidasDisponiblesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPartidasDisponiblesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPartidasDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Partida[] RecuperarPartidasDisponiblesResult;
        
        public RecuperarPartidasDisponiblesResponse()
        {
        }
        
        public RecuperarPartidasDisponiblesResponse(ServicioAhorcado.Partida[] RecuperarPartidasDisponiblesResult)
        {
            this.RecuperarPartidasDisponiblesResult = RecuperarPartidasDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPartidasJugador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPartidasJugadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string idJugador;
        
        public RecuperarPartidasJugadorRequest()
        {
        }
        
        public RecuperarPartidasJugadorRequest(string idJugador)
        {
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPartidasJugadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPartidasJugadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.PartidaGanada[] RecuperarPartidasJugadorResult;
        
        public RecuperarPartidasJugadorResponse()
        {
        }
        
        public RecuperarPartidasJugadorResponse(ServicioAhorcado.PartidaGanada[] RecuperarPartidasJugadorResult)
        {
            this.RecuperarPartidasJugadorResult = RecuperarPartidasJugadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarCategoria", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarCategoriaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idCategoria;
        
        public RecuperarCategoriaRequest()
        {
        }
        
        public RecuperarCategoriaRequest(int idCategoria)
        {
            this.idCategoria = idCategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarCategoriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarCategoriaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Categoria RecuperarCategoriaResult;
        
        public RecuperarCategoriaResponse()
        {
        }
        
        public RecuperarCategoriaResponse(ServicioAhorcado.Categoria RecuperarCategoriaResult)
        {
            this.RecuperarCategoriaResult = RecuperarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPalabra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPalabraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idPalabra;
        
        public RecuperarPalabraRequest()
        {
        }
        
        public RecuperarPalabraRequest(int idPalabra)
        {
            this.idPalabra = idPalabra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarPalabraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarPalabraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServicioAhorcado.Palabra RecuperarPalabraResult;
        
        public RecuperarPalabraResponse()
        {
        }
        
        public RecuperarPalabraResponse(ServicioAhorcado.Palabra RecuperarPalabraResult)
        {
            this.RecuperarPalabraResult = RecuperarPalabraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarEstadoPartida", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarEstadoPartidaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idPartida;
        
        public ActualizarEstadoPartidaRequest()
        {
        }
        
        public ActualizarEstadoPartidaRequest(int estado, int idPartida)
        {
            this.estado = estado;
            this.idPartida = idPartida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarEstadoPartidaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarEstadoPartidaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActualizarEstadoPartidaResult;
        
        public ActualizarEstadoPartidaResponse()
        {
        }
        
        public ActualizarEstadoPartidaResponse(bool ActualizarEstadoPartidaResult)
        {
            this.ActualizarEstadoPartidaResult = ActualizarEstadoPartidaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceAhorcadoChannel : ServicioAhorcado.IServiceAhorcado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceAhorcadoClient : System.ServiceModel.ClientBase<ServicioAhorcado.IServiceAhorcado>, ServicioAhorcado.IServiceAhorcado
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceAhorcadoClient() : 
                base(ServiceAhorcadoClient.GetDefaultBinding(), ServiceAhorcadoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceAhorcado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), ServiceAhorcadoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceAhorcadoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAhorcadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.VerificarJugadorResponse> VerificarJugadorAsync(ServicioAhorcado.VerificarJugadorRequest request)
        {
            return base.Channel.VerificarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RegistrarJugadorResponse> RegistrarJugadorAsync(ServicioAhorcado.RegistrarJugadorRequest request)
        {
            return base.Channel.RegistrarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.ModificarJugadorResponse> ModificarJugadorAsync(ServicioAhorcado.ModificarJugadorRequest request)
        {
            return base.Channel.ModificarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.recuperarJugadorResponse> recuperarJugadorAsync(ServicioAhorcado.recuperarJugadorRequest request)
        {
            return base.Channel.recuperarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.ActualizarPuntosResponse> ActualizarPuntosAsync(ServicioAhorcado.ActualizarPuntosRequest request)
        {
            return base.Channel.ActualizarPuntosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.ActualizarProgresoPartidaResponse> ActualizarProgresoPartidaAsync(ServicioAhorcado.ActualizarProgresoPartidaRequest request)
        {
            return base.Channel.ActualizarProgresoPartidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RegistrarPartidaResponse> RegistrarPartidaAsync(ServicioAhorcado.RegistrarPartidaRequest request)
        {
            return base.Channel.RegistrarPartidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RegistrarJugadorEnPartidaResponse> RegistrarJugadorEnPartidaAsync(ServicioAhorcado.RegistrarJugadorEnPartidaRequest request)
        {
            return base.Channel.RegistrarJugadorEnPartidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPartidasDisponiblesResponse> RecuperarPartidasDisponiblesAsync(ServicioAhorcado.RecuperarPartidasDisponiblesRequest request)
        {
            return base.Channel.RecuperarPartidasDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPartidasJugadorResponse> RecuperarPartidasJugadorAsync(ServicioAhorcado.RecuperarPartidasJugadorRequest request)
        {
            return base.Channel.RecuperarPartidasJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RecuperarCategoriaResponse> RecuperarCategoriaAsync(ServicioAhorcado.RecuperarCategoriaRequest request)
        {
            return base.Channel.RecuperarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.RecuperarPalabraResponse> RecuperarPalabraAsync(ServicioAhorcado.RecuperarPalabraRequest request)
        {
            return base.Channel.RecuperarPalabraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioAhorcado.ActualizarEstadoPartidaResponse> ActualizarEstadoPartidaAsync(ServicioAhorcado.ActualizarEstadoPartidaRequest request)
        {
            return base.Channel.ActualizarEstadoPartidaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAhorcado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAhorcado))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:49522/ServiceAhorcado.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceAhorcadoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceAhorcado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceAhorcadoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceAhorcado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceAhorcado,
        }
    }
}
